### ISSUE TITLE
ledreports doesn't work

### ISSUE THREAD

**Issue by odama626** [rolfschr/GSWL-ecosystem#2]
$LEDGER_ECOSYSTEM_DIR seems to always return . for me in bash

changing alias to this seemed to fix it for me (thanks to stackoverflow)
```
LEDGER_ECOSYSTEM_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
```

edit: by the way, just started with ledger and I am loving your guide.  Thank you!

**Comment by rolfschr** [comment]
Hi,

Thanks for this. It does return `.` when you are in the ecosystem dir. One is supposed to source the alias file while being inside the [private repo](https://github.com/rolfschr/GSWL-private). When you are somewhere else, it works as expected. 

```
$ cd /home/rolf/src/GSWL-ecosystem
$ source alias 
$ echo $LEDGER_ECOSYSTEM_DIR 
.
$ cd /tmp 
$ source /home/rolf/src/GSWL-ecosystem/alias 
$ echo $LEDGER_ECOSYSTEM_DIR 
/home/rolf/src/GSWL-ecosystem
```

So I assume this is working fine. Let me know if it doesn't.
