### ISSUE TITLE
Scrolling inside ledreports

### ISSUE THREAD

**Issue by DerBeutlin** [rolfschr/GSWL-ecosystem#6]
~It would be nice if scrolling (using the mouse or using key-strokes) would be possible in the ledreports section as most reports are larger than one screenful.~
Totally possible if one configures tmux correctly using
```
set -g mouse on        #For tmux version 2.1 and up
set -g mode-mouse on   #For tmux versions < 2.1
``

**Comment by rolfschr** [comment]
Yeah, you can also use tmux' visual/copy mode to scroll up and down.
