### ISSUE TITLE
Ledger accounts with spaces brackets inside them cause issue in convert.py

### ISSUE THREAD

**Issue by mattig7** [rolfschr/GSWL-ecosystem#7]
One of my accounts had spaces and then brackets in the name (eg "Assets:8367424(TransactionAcct)". When this is processed in convert.py, it causes an error, because the account is not passed to the ledger command with quotes around the account name. Ie, the variable 'cmd', executed on line 137 of convert.py is of the form "ledger Assets:8367424(TransactionAcct)"
Note that the error does not stop execution - it mainly just ignores lines (unreliability) or doesn't fill the full account name into the final file. 
There is usually no error message because the script immediately pulls up a view of the converted files, obscuring any errors written to stdout.

Suggested solution:
Problem is fixed for me If you simply add \" around the {} on line 124 (the bit that adds the account name after --account when creating the ledger command, cmd). Tested fixing the spaces, not the brackets.

**Comment by mattig7** [comment]
PS Great work overall in creating this (ecosystem, private, and the book). I'm finding it very useful for automation in ledger, and picked up lots of cool tricks. Cheers!

**Comment by rolfschr** [comment]
Hi, 

thanks for the feedback. I patched it as you suggested. Please close the issue if it works out for you.
